language: bash

services:
  - docker

before_script:
  - echo "Starting Docker build process..."

script:
  - set -x
  # Build images
  - docker build -t $DOCKER_USERNAME/udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t $DOCKER_USERNAME/udagram-api-user ./udagram-api-user
  - docker build -t $DOCKER_USERNAME/udagram-api-feed ./udagram-api-feed
  - docker build -t $DOCKER_USERNAME/udagram-frontend ./udagram-frontend

  # Tag images
  - docker tag $DOCKER_USERNAME/udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:${TRAVIS_BUILD_NUMBER}
  - docker tag $DOCKER_USERNAME/udagram-api-user $DOCKER_USERNAME/udagram-api-user:${TRAVIS_BUILD_NUMBER}
  - docker tag $DOCKER_USERNAME/udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:${TRAVIS_BUILD_NUMBER}
  - docker tag $DOCKER_USERNAME/udagram-frontend $DOCKER_USERNAME/udagram-frontend:${TRAVIS_BUILD_NUMBER}

  # Push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-reverseproxy:${TRAVIS_BUILD_NUMBER}
  - docker push $DOCKER_USERNAME/udagram-api-user:${TRAVIS_BUILD_NUMBER}
  - docker push $DOCKER_USERNAME/udagram-api-feed:${TRAVIS_BUILD_NUMBER}
  - docker push $DOCKER_USERNAME/udagram-frontend:${TRAVIS_BUILD_NUMBER}
