language: minimal

services:
  - docker

before_script:
  # Log in to DockerHub
  - echo "1305P@ul" | docker login -u "pauldang" --password-stdin

script:
  # Build Docker images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend

  # Tag Docker images
  - docker tag udagram-api-feed sudkul/udagram-api-feed:v1
  - docker tag udagram-api-user sudkul/udagram-api-user:v1
  - docker tag udagram-api-feed sudkul/udagram-api-feed:v1
  - docker tag udagram-frontend sudkul/udagram-frontend:v1

deploy:
  provider: script
  script: |
    docker push sudkul/udagram-api-feed:v1
    docker push sudkul/udagram-api-user:v1
    docker push sudkul/udagram-api-feed:v1
    docker push sudkul/udagram-frontend:v1
  on:
    branch: main
