language: bash

services:
  - docker

before_script:
  - echo "Starting Docker build process..."

script:
  # Build images
  - docker build -t $DOCKER_USERNAME/reverseproxy ./reverseproxy
  - docker build -t $DOCKER_USERNAME/udagram-api-user ./udagram-api-user
  - docker build -t $DOCKER_USERNAME/udagram-api-feed ./udagram-api-feed
  - docker build -t $DOCKER_USERNAME/udagram-frontend ./udagram-frontend

  # Tag images
  - docker tag $DOCKER_USERNAME/reverseproxy $DOCKER_USERNAME/reverseproxy:v1
  - docker tag $DOCKER_USERNAME/udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag $DOCKER_USERNAME/udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag $DOCKER_USERNAME/udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1

  # Push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/reverseproxy:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:v1
